services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
#    env_file:
#      - .env
    ports:
      - "5090:8080"
    volumes:
      - open-webui:/app/backend/data
volumes:
  open-webui:
